export const DEFAULT_SWARM_PRUNE_INTERVAL: number = 30;
export const DEFAULT_SWARM_PRUNE_INTERVAL_EXTENDED: number = 60;
export const DEFAULT_SWARM_ID_BROADCAST_INTERVAL: number = 30;
export const DEFAULT_SWARM_ID_BROADCAST_INTERVAL_EXTENDED: number = 60;
export const DEFAULT_ROBOT_ALIVE_INTERVAL: number = 360;
export const DEFAULT_ROBOT_ALIVE_INTERVAL_EXTENDED: number = 600;
