# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
              env: # Or as an environment variable
                  mqtt_host: ${{ secrets.MQTT_HOST }}
                  mqtt_user: ${{ secrets.MQTT_USER }}
                  mqtt_pass: ${{ secrets.MQTT_PASS }}
                  CI: true
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
